# This program prints Hello, world!

In [1]:
print('Hello, world!')


Hello, world!


# This program adds two numbers



In [2]:

num1 = 1.5
num2 = 6.3
sum = num1 + num2

# Display the sum
print(sum)

7.8


# Python Program to calculate the square root



In [3]:

num = float(input('Enter a number: '))

num_sqrt = num ** 0.5
print(num_sqrt)

Enter a number: 9
3.0



Python Program to Calculate the Area of a Triangle
In this program, you'll learn to calculate the area of a triangle and display it.



In [5]:

#vertices
a = float(input('Enter first side: '))
b = float(input('Enter second side: '))
c = float(input('Enter third side: '))

# calculate the semi-perimeter
s = (a + b + c) / 2

# calculate the area
area = (s*(s-a)*(s-b)*(s-c)) ** 0.5
print(area)

Enter first side: 4
Enter second side: 4
Enter third side: 4
6.928203230275509


# Solve the quadratic equation ax**2 + bx + c = 0

In [6]:


# import complex math module
import cmath

a = 1
b = 5
c = 6

# calculate the discriminant
d = (b**2) - (4*a*c)

# find two solutions
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)

print('The solution are {0} and {1}'.format(sol1,sol2))


The solution are (-3+0j) and (-2+0j)


# Swap two variables

In [7]:
x = 5
y = 10

x, y = y, x
print("x =", x)
print("y =", y)

x = 10
y = 5


# Python program to check if the input number is odd or even.


In [8]:
num = int(input("Enter a number: "))
if (num % 2) == 0:
   print("{0} is Even".format(num))
else:
   print("{0} is Odd".format(num))

Enter a number: 26
26 is Even


# Check whether its a prime number

In [10]:

num = int(input("Enter a number: "))

if num == 1:
    print(num, "is not a prime number")
elif num > 1:
   for i in range(2,num):
       if (num % i) == 0:
           print(num,"is not a prime number")
           break
   else:
       print(num,"is a prime number")
else:
   print(num,"is not a prime number")

Enter a number: 11
11 is a prime number


# Factorial of a number

In [11]:

num = int(input("Enter a number: "))

factorial = 1

if num < 0:
   print("Sorry, factorial does not exist for negative numbers")
elif num == 0:
   print("The factorial of 0 is 1")
else:
   for i in range(1,num + 1):
       factorial = factorial*i
   print(factorial)

Enter a number: 4
24


Check whether a number is an armstrong number

In [16]:
# take input from the user
num = int(input("Enter a number: "))

# initialize sum
sum = 0

# find the sum of the cube of each digit
temp = num
while temp > 0:
   digit = temp % 10
   sum += digit ** 3
   temp //= 10

# display the result
if num == sum:
   print(num,"is an Armstrong number")
else:
   print(num,"is not an Armstrong number")

Enter a number: 153
153 is an Armstrong number


# Sum of first n natural number

In [18]:
num = int(input())

if num < 0:
   print("Enter a positive number")
else:
   sum = 0
   while(num > 0):
       sum += num
       num -= 1
   print("The sum is", sum)

6
The sum is 21


# Python Program to find the factors of a number


In [19]:

def print_factors(x):
   print("The factors of",x,"are:")
   for i in range(1, x + 1):
       if x % i == 0:
           print(i)

print_factors(9)

The factors of 9 are:
1
3
9


# Palindrome Check

In [25]:
def palindrome(string):
  if string == string[::-1]:
    print('Its a palindrome')
  else:
    print('Not a palindrome')

palindrome('malayalam')

Its a palindrome


# Check for Perfect Number

In [39]:
def perfectNumber(number):
    sum = 0
    for x in range(1, number):
        if number % x == 0:
            sum += x
    return sum == number

if __name__ == '__main__':
    print(perfectNumber(6)) # True
    print(perfectNumber(3)) # False

True
False


# Numpy Intro

In [27]:
import numpy as np

# we have a function arange() which makes an array of the specified dimension. Example:
myArray = np.arange(20)
print(myArray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [28]:
# an array from 10 to 20
myArray = np.arange(10, 20) # [10 11 12 13 14 15 16 17 18 19]
print(myArray)

[10 11 12 13 14 15 16 17 18 19]


In [29]:
# an array from 10 to 20 with 2 steps
myArray = np.arange(10, 20, 2)
print(myArray)  

[10 12 14 16 18]


In [30]:
# reshape() helps to reshape our NumPy array
myArray = np.arange(20)
# syntax: reshape(number_of_rows, number_of_columns)
myArray = myArray.reshape(4, 5)
print(myArray)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [31]:
# shape returns the shape of the array. The length of shape tuple is called as rank (or dimension)
print(myArray.shape) 

(4, 5)


In [32]:
# ndim returns the dimension (rank) of the array
print(myArray.ndim) 

2


In [33]:
# size returns the total number of elements in the array
print(myArray.size)  

20


In [34]:
# zeros creates an array will all zeros
myArray = np.zeros((3, 4))
print(myArray)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
# ones creates an array with all ones
myArray = np.ones((3, 4))
print(myArray)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
# numpy random module helps to initialize array with random values
myArray = np.random.rand(3, 4)
print(myArray)

[[0.53697984 0.65368782 0.72623189 0.59250503]
 [0.87009843 0.95371987 0.69434202 0.02590512]
 [0.04777574 0.25354941 0.19812992 0.62655315]]
